### PR TITLE
Add list of providers to setup wizard

### PR DESCRIPTION
**Pull request by juliusknorr**
ToDo:

- [x] Filter list by free accounts/country

2017-06-13-151258_750x507_scrot
2017-06-13-151325_750x507_scrot

### CODE REVIEW

**Comment by juliusknorr** [comment]
- [x] Remove owncloudprovidermodel (leftover from trying to use qlistview)
- [x] Don't build with provider list when PROVIDER_LIST is not defined

**Comment by rullzer** [comment]
@jancborchardt is this looking good for you?

**Comment by juliusknorr** [comment]
Some more things that came up in a call with @jospoortvliet 
- [ ] Free plans should be shown by default
- [ ] Show providers for the current users country first

**Comment by jancborchardt** [comment]
Very nice already! Just some things:

- The two buttons currently almost look like they belong to the server address input field. They should have a header on top of them saying: "Don't have a Nextcloud server yet?" and also move a bit closer together.

- What's that "all" dropdown on the top right?

- is it possible to put the "Free plans" checkbox and "All" dropdown in the bottom row where Back and Next are to save space?

- I'd say we simply show free plans by default too, and add a badge if a provider has them. Trying out stuff for free is an important step for any user. :) (we don't even need that checkbox)

**Comment by jancborchardt** [comment]
The goal basically is through filtering, geolocation and prioritization to have 3 great choices directly in there. People should not need to scroll and search for long. :)

**Comment by juliusknorr** [comment]
> The goal basically is through filtering, geolocation and prioritization to have 3 great choices directly in there. People should not need to scroll and search for long. :)

I guess we should just show the providers for the current users location, so the "All" dropdown will show the users country by default.

**Comment by juliusknorr** [comment]
@jancborchardt I addressed your comments.

It now shows the providers of the users country, free only on startup. 
2017-08-06-093438_750x531_scrot
2017-08-06-104903_750x531_scrot

>is it possible to put the "Free plans" checkbox and "All" dropdown in the bottom row where Back and Next are to save space?

I'm not aware of any possibility to do that. Maybe @rullzer has an idea, but to me it seems like the QWizard is limited to adding buttons on the bottom row.

> The goal basically is through filtering, geolocation and prioritization to have 3 great choices directly in there. People should not need to scroll and search for long. :)

Should we introduce some flag like "featured" provider so they show up on top of the list? I remember there has been some discussion about that somewhere, but that was quite a controversial topic iirc. cc @jospoortvliet

**Comment by jancborchardt** [comment]
Nice! Only a few details I'd change:

- Instead of "Search for a hosting provider" call the button "Choose a provider"
- The list would look nicer & more modern without the alternating white-grey background. A little more vertical whitespace would probably be enough.
- The "Free" tag can be a bit more explainable saying "Offers free plans" and be below the "more info"/"Register" button
- Is it possible to remove the whitespace under the scrollable container between the horizontal line? Or also remove the horizontal line?

**Comment by rullzer** [comment]
@juliushaertl @jancborchardt 

> > is it possible to put the "Free plans" checkbox and "All" dropdown in the bottom row where Back and Next are to save space?
>
> I'm not aware of any possibility to do that. Maybe @rullzer has an idea, but to me it seems like the QWizard is limited to adding buttons on the bottom row.

Yep not easily without fighting with the whole wizard layout. I would leave that for later.

> Is it possible to remove the whitespace under the scrollable container between the horizontal line? Or also remove the horizontal line?

There is a spacer there. Also removing that is not really easy as then it will look very strange and sticky if the wizard window is bigger or smaller etc.

**Comment by juliusknorr** [comment]
Closing in favour of https://github.com/nextcloud/gsoc_client/pull/17

**Pull request closed without merging**
